### ISSUE TITLE
Spamming journalctl,..

### ISSUE THREAD

**Issue by gpelz-graph-it** [canonical/desktop-security-center#71]
I'm on Ubuntu 24.04 and I Installed the desktop-security-center by calling:
```
root@pc068:~# snap refresh snapd --candidate
root@pc068:~# snap install desktop-security-center
root@pc068:~# snap install prompting-client
```
and now apparmor is spamming the journalctl with:
```
Sep 18 13:10:40 pc068 kernel: audit: type=1400 audit(1726657840.181:318): apparmor="DENIED" operation="open" class="file" profile="snap.prompting-client.daemon" name="/sys/fs/cgroup/user.slice/user-0.slice/user@0.service/app.slice/cpu.max" pid=4728 comm="prompting-clien" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 18 13:10:40 pc068 kernel: audit: type=1400 audit(1726657840.181:319): apparmor="DENIED" operation="open" class="file" profile="snap.prompting-client.daemon" name="/sys/fs/cgroup/user.slice/user-0.slice/user@0.service/cpu.max" pid=4728 comm="prompting-clien" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 18 13:10:40 pc068 kernel: audit: type=1400 audit(1726657840.181:320): apparmor="DENIED" operation="open" class="file" profile="snap.prompting-client.daemon" name="/sys/fs/cgroup/user.slice/user-0.slice/cpu.max" pid=4728 comm="prompting-clien" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
Sep 18 13:10:40 pc068 kernel: audit: type=1400 audit(1726657840.181:321): apparmor="DENIED" operation="open" class="file" profile="snap.prompting-client.daemon" name="/sys/fs/cgroup/user.slice/cpu.max" pid=4728 comm="prompting-clien" requested_mask="r" denied_mask="r" fsuid=0 ouid=0
```
every 2 seconds. (going to deinstall this now, but thought I let you know of the problem)

**Comment by sminez** [comment]
Thanks for reporting this @gpelz-graph-it. Were you seeing this the log spam after enabling the feature via the security center? Or was it immediate on installing the snaps themselves?

**Comment by gpelz-graph-it** [comment]
Sorry, forgot to mention. This happens as soon as the feature is enabled in the security center. After disabling the feature in the security center, the messages do not appear anymore.

**Comment by sminez** [comment]
Thanks for confirming :+1: 

This is very odd...the 2 second interval sounds suspiciously close to the [restart-delay](https://github.com/canonical/prompting-client/blob/main/snap/snapcraft.yaml#L39) that the prompting client sets with systemd, implying its in a crash loop. But that shouldn't be happening as we should only get restarted if we exit cleanly. The only place we should be exiting 0 is if we are unable to see `DISPLAY` or `WAYLAND_DISPLAY` in the environment when the daemon is launched (as then we would be unable to serve the UI).

I'll look into it and see if I can work out what the cause of this is. @sergio-costas I have a nagging feeling that this might be related to the issue you told me about with getting snapd-desktop-integration to work as a snapped user daemon?

**Comment by gpelz-graph-it** [comment]
@sminez : here you go:
```
root@pc068:~# uname -rv
6.8.0-45-generic #45-Ubuntu SMP PREEMPT_DYNAMIC Fri Aug 30 12:02:04 UTC 2024
root@pc068:~# curl -s --unix-socket /run/snapd.socket "http://localhost/v2/system-info" | jq '.result.features["apparmor-prompting"]'
{
  "supported": true,
  "enabled": true
}
```

**Comment by sminez** [comment]
@gpelz-graph-it sorry about the delay in addressing this. I think I've tracked down the source of the read calls that are causing the denials you're seeing: they're from [Tokio attempting to set up its thread pool](https://github.com/tokio-rs/tokio/blob/679d7657dc267a4d6472597c91cdda8792cf9e97/tokio/src/loom/std/mod.rs#L90-L122)

`std::thread::available_parallelism` wont work under snap sandboxing anyway (documented [here](https://doc.rust-lang.org/std/thread/fn.available_parallelism.html#limitations)) so I think the best thing to do is to specify the `TOKIO_WORKER_THREADS` environment variable as described [here](https://docs.rs/tokio/latest/tokio/runtime/struct.Builder.html#method.worker_threads). That gets rid of the denails for me so I'll get that added to the snap packaging so we don't spam the log in this way.

One thing I'm not sure about though is why you are seeing this every two seconds. That side of things I can't reproduce, but a colleague managed when running the prompting client without a graphical session in place. As I mentioned above, the client forces a restart at a 2s interval with systemd in order to wait for `DISPLAY` or `WAYLAND_DISPLAY` to be set so that we will be able to spawn the Flutter UI.

This is something I should have checked earlier, but do you have a live X11 or WAYLAND session when you are seeing the log spam? I see from your initial description of the issue that you were running as root which may also cause some issues I think. @olivercalder I know we spoke about prompting for `root` previously but I forget the details now. Is there anything on that front we should be considering do you know?

**Comment by sminez** [comment]
@gpelz-graph-it changes from the PR above are now available on the `1/edge` channel if you are able to try it out?
```
$ snap refresh prompting-client --channel=1/edge
```

This gets rid of the apparmor denials for in our local testing but like I mentioned above, the only way we've been able to reproduce the 2s interval log spam is to run the client without an active desktop session. So that side things is still something I'm looking into.

**Comment by olivercalder** [comment]
Sorry for the delay, and thanks for the fix for `TOKIO_WORKER_THREADS`! It would seem to me that there must be other snaps which also legitimately want to query cgroup information to know best to run, perhaps this is something we should look into allowing either via an interface or implicitly. It would be a shame if someone running a snap of a server would only get single-threaded performance.

Regarding running as root, there are a few considerations:
- Since the prompting client runs as a user daemon, there needs to be a systemd user session, which there is not for root, so the client doesn't work when running as root (afaik)
  - In fact, unless there's a prompting client running in an active user (non-root) session, I don't think snapd will let you enable prompting
- We currently only prompt for the home interface, and for root that would be prompting for files in `/root`
- Most of the time, if you're running a snap as root, it's because it's a system daemon, and there's no user actively logged in as root which (even if the prompting client worked for root, which it doesn't) can answer the prompts for root
  - So, a system daemon which caused a prompt would be locked up waiting for prompts to timeout, either in snapd, the kernel, or the application, since no reply would ever come
  - Also, system daemons should never be using the `home` interface or treating `/root` as a user home directory, though technically this is supported
- Root has more elevated privileges, so we want to put extra protections against non-daemon snaps running as root

For these reasons, the current approach is for snapd to deny any prompt request received from the kernel which is destined for the root user. So no prompts are ever created, the snapd listener just sees the request and immediately sends a denial.

We will likely need to review this decision again if/when we expand prompting to interfaces which are reasonable to be used by system daemons.

**Comment by Selur** [comment]
I had a terminal open as root. (To see journalctl and other stuff,..)
I plan to do some testing on Tuesday.

**Comment by gpelz-graph-it** [comment]
Did find some time and installed the tools:
(connected via ssh to the system)
```
root@pc068:~# snap refresh snapd --candidate
root@pc068:~# snap install desktop-security-center
root@pc068:~# snap refresh prompting-client --channel=1/edge
```
then connected via x11vnc to the system openend ans started the Security Center
Now instead of the appamor messages I see every two seconds 'Started snap.prompting-client.daemon.service':
```
Okt 14 07:45:57 pc068 systemd[5284]: Started snap.prompting-client.daemon.service - Service for snap application prompting-client.daemon.
░░ Subject: A start job for unit UNIT has finished successfully
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ A start job for unit UNIT has finished successfully.
░░ 
░░ The job identifier is 2715.
Okt 14 07:45:59 pc068 systemd[5284]: snap.prompting-client.daemon.service: Scheduled restart job, restart counter is at 16.
░░ Subject: Automatic restarting of a unit has been scheduled
░░ Defined-By: systemd
░░ Support: http://www.ubuntu.com/support
░░ 
░░ Automatic restarting of the unit UNIT has been scheduled, as the result for
░░ the configured Restart= setting for the unit.
Okt 14 07:45:59 pc068 systemd[5284]: Started snap.prompting-client.daemon.service - Service for snap application prompting-client.daemon.
```

**Comment by sminez** [comment]
I suspect that the use of `x11vnc` is going to be the issue here. The prompting client daemon needs to detect if it will be able to spawn the UI which is where the startup checks for the `DISPLAY` and `WAYLAND_DISPLAY` come in. I don't have much experience with `x11vnc` I'm afraid, but the restart you are still seeing is down to those variables not being set.

If they're not present there is no way for us to spawn the user interface and the variables not being present on startup _is_ expected as the daemon can end up being started by systemd before the graphical session is in place.

Are you able to replicate this behaviour at all on a system that you are not connecting to via `x11vnc`?

**Comment by Selur** [comment]
Yes, I encountered this first when sitting directly at the system, just connected via x11vnc trying to do some more testing. I can probably look at it again directly at the machine on Tuesday.

**Comment by gpelz-graph-it** [comment]
Seems to be fixed (after installing everything like in the first post) when starting the security center I see:
```
Nov 06 07:39:59 pc068 kernel: audit: type=1400 audit(1730875199.156:559): apparmor="DENIED" operation="open" class="file" profile="snap.desktop-security-center.desktop-security-center" name="/etc/xattr.conf" pid=30663 comm="cp" requested_mask="r" denied_mask="r" fsuid=2009 ouid=0
Nov 06 07:39:59 pc068 security_center[30593]: Not loading module "atk-bridge": The functionality is provided by GTK natively. Please try to not load it.
Nov 06 07:39:59 pc068 security_center[30593]: GTK+ module /snap/desktop-security-center/32/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
                                              GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Nov 06 07:39:59 pc068 security_center[30593]: Failed to load module "canberra-gtk-module"
Nov 06 07:39:59 pc068 security_center[30593]: GTK+ module /snap/desktop-security-center/32/gnome-platform/usr/lib/gtk-2.0/modules/libcanberra-gtk-module.so cannot be loaded.
                                              GTK+ 2.x symbols detected. Using GTK+ 2.x and GTK+ 3 in the same process is not supported.
Nov 06 07:39:59 pc068 security_center[30593]: Failed to load module "canberra-gtk-module"
Nov 06 07:39:59 pc068 dbus-daemon[2513]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/example/security_center" interface="org.gtk.Actions" member="DescribeAll" name=":1.39" mask="receive" pid=30593 label="snap.desktop-security-center.desktop-security-center" peer_pid=2737 peer_label="unconfined"
Nov 06 07:39:59 pc068 dbus-daemon[2513]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/example/security_center" interface="org.freedesktop.DBus.Properties" member="GetAll" name=":1.39" mask="receive" pid=30593 label="snap.desktop-security-center.desktop-security-center" peer_pid=2737 peer_label="unconfined"
Nov 06 07:39:59 pc068 dbus-daemon[2513]: apparmor="DENIED" operation="dbus_method_call"  bus="session" path="/com/example/security_center/window/1" interface="org.gtk.Actions" member="DescribeAll" name=":1.39" mask="receive" pid=30593 label="snap.desktop-security-center.desktop-security-center" peer_pid=2737 peer_label="unconfined"
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.520:560): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=203 compat=0 ip=0x746f71919531 code=0x50000
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.520:561): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=141 compat=0 ip=0x746f7199878b code=0x50000
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.520:562): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=203 compat=0 ip=0x746f71919531 code=0x50000
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.520:563): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=203 compat=0 ip=0x746f71919531 code=0x50000
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.523:564): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=203 compat=0 ip=0x746f71919531 code=0x50000
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.537:565): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=141 compat=0 ip=0x746f7199878b code=0x50000
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.539:566): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=141 compat=0 ip=0x746f7199878b code=0x50000
Nov 06 07:39:59 pc068 kernel: audit: type=1326 audit(1730875199.541:567): auid=2009 uid=2009 gid=2009 ses=3 subj=snap.desktop-security-center.desktop-security-center pid=30593 comm="security_center" exe="/snap/desktop-security-center/32/bin/security_center" sig=0 arch=c000003e syscall=141 compat=0 ip=0x746f7199878b code=0x50000
Nov 06 07:39:59 pc068 security_center[30593]: GtkWindow must be shown AFTER registering plugins. In `linux/my_application.cc`, change `my_application_activate()` to call `gtk_widget_show(window)` after calling `fl_register_plugins(view)`.
Nov 06 07:39:59 pc068 security_center[30593]: Setting up a Handy window failed. A normal GTK window will be used instead. See README.md for more detailed instructions.
```
when enabling the app notification unlike before, I don't see a message about the snap.prompting-client.daemon.service
